#!/bin/bash

# Do a so called "needle sweep", gradually, while the indicator lights are going crazy
mosquitto_pub -h localhost -t engine/rpm/state -m "0"
mosquitto_pub -h localhost -t engine/egt/state -m "0"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "0"
mosquitto_pub -h localhost -t engine/boost/state -m "0"
mosquitto_pub -h localhost -t engine/coolant/state -m "0"
mosquitto_pub -h localhost -t engine/fuel/state -m "0"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "00"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "00"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:000000
trip:000000"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "5"
mosquitto_pub -h localhost -t engine/egt/state -m "1"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "1"
mosquitto_pub -h localhost -t engine/boost/state -m "1"
mosquitto_pub -h localhost -t engine/coolant/state -m "1"
mosquitto_pub -h localhost -t engine/fuel/state -m "1"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "11"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "11"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
new_content="odo:111111
trip:111111"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "10"
mosquitto_pub -h localhost -t engine/egt/state -m "2"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "2"
mosquitto_pub -h localhost -t engine/boost/state -m "2"
mosquitto_pub -h localhost -t engine/coolant/state -m "2"
mosquitto_pub -h localhost -t engine/fuel/state -m "2"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "22"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "22"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:222222
trip:2222222"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "15"
mosquitto_pub -h localhost -t engine/egt/state -m "3"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "3"
mosquitto_pub -h localhost -t engine/boost/state -m "3"
mosquitto_pub -h localhost -t engine/coolant/state -m "3"
mosquitto_pub -h localhost -t engine/fuel/state -m "3"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "33"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "33"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
new_content="odo:333333
trip:333333"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "20"
mosquitto_pub -h localhost -t engine/egt/state -m "4"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "4"
mosquitto_pub -h localhost -t engine/boost/state -m "4"
mosquitto_pub -h localhost -t engine/coolant/state -m "4"
mosquitto_pub -h localhost -t engine/fuel/state -m "4"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "44"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "44"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:444444
trip:444444"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "25"
mosquitto_pub -h localhost -t engine/egt/state -m "5"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "5"
mosquitto_pub -h localhost -t engine/boost/state -m "5"
mosquitto_pub -h localhost -t engine/coolant/state -m "5"
mosquitto_pub -h localhost -t engine/fuel/state -m "5"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "55"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "55"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
new_content="odo:555555
trip:555555"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "30"
mosquitto_pub -h localhost -t engine/egt/state -m "6"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "6"
mosquitto_pub -h localhost -t engine/boost/state -m "6"
mosquitto_pub -h localhost -t engine/coolant/state -m "6"
mosquitto_pub -h localhost -t engine/fuel/state -m "6"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "66"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "66"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:666666
trip:666666"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "35"
mosquitto_pub -h localhost -t engine/egt/state -m "7"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "7"
mosquitto_pub -h localhost -t engine/boost/state -m "7"
mosquitto_pub -h localhost -t engine/coolant/state -m "7"
mosquitto_pub -h localhost -t engine/fuel/state -m "7"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "77"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "77"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
new_content="odo:777777
trip:777777"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "40"
mosquitto_pub -h localhost -t engine/egt/state -m "8"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "8"
mosquitto_pub -h localhost -t engine/boost/state -m "8"
mosquitto_pub -h localhost -t engine/coolant/state -m "8"
mosquitto_pub -h localhost -t engine/fuel/state -m "8"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "88"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "88"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:888888
trip:888888"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "45"
mosquitto_pub -h localhost -t engine/egt/state -m "9"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "9"
mosquitto_pub -h localhost -t engine/boost/state -m "9"
mosquitto_pub -h localhost -t engine/coolant/state -m "9"
mosquitto_pub -h localhost -t engine/fuel/state -m "9"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "99"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "99"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
new_content="odo:999999
trip:999999"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "50"
mosquitto_pub -h localhost -t engine/egt/state -m "10"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "10"
mosquitto_pub -h localhost -t engine/boost/state -m "10"
mosquitto_pub -h localhost -t engine/coolant/state -m "10"
mosquitto_pub -h localhost -t engine/fuel/state -m "10"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "99"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "99"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
# sleep 0.001

# After the sweep, go to normal state, gradually
mosquitto_pub -h localhost -t engine/rpm/state -m "45"
mosquitto_pub -h localhost -t engine/egt/state -m "9"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "9"
mosquitto_pub -h localhost -t engine/boost/state -m "9"
mosquitto_pub -h localhost -t engine/coolant/state -m "9"
mosquitto_pub -h localhost -t engine/fuel/state -m "9"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "99"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "99"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "40"
mosquitto_pub -h localhost -t engine/egt/state -m "8"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "8"
mosquitto_pub -h localhost -t engine/boost/state -m "8"
mosquitto_pub -h localhost -t engine/coolant/state -m "8"
mosquitto_pub -h localhost -t engine/fuel/state -m "8"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "88"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "88"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:888888
trip:888888"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "35"
mosquitto_pub -h localhost -t engine/egt/state -m "7"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "7"
mosquitto_pub -h localhost -t engine/boost/state -m "7"
mosquitto_pub -h localhost -t engine/coolant/state -m "7"
mosquitto_pub -h localhost -t engine/fuel/state -m "7"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "77"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "77"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
new_content="odo:777777
trip:777777"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "30"
mosquitto_pub -h localhost -t engine/egt/state -m "6"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "6"
mosquitto_pub -h localhost -t engine/boost/state -m "6"
mosquitto_pub -h localhost -t engine/coolant/state -m "6"
mosquitto_pub -h localhost -t engine/fuel/state -m "6"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "66"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "66"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:666666
trip:666666"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "25"
mosquitto_pub -h localhost -t engine/egt/state -m "5"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "5"
mosquitto_pub -h localhost -t engine/boost/state -m "5"
mosquitto_pub -h localhost -t engine/coolant/state -m "5"
mosquitto_pub -h localhost -t engine/fuel/state -m "5"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "55"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "55"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
new_content="odo:555555
trip:555555"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "20"
mosquitto_pub -h localhost -t engine/egt/state -m "4"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "4"
mosquitto_pub -h localhost -t engine/boost/state -m "4"
mosquitto_pub -h localhost -t engine/coolant/state -m "4"
mosquitto_pub -h localhost -t engine/fuel/state -m "4"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "44"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "44"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:444444
trip:444444"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "15"
mosquitto_pub -h localhost -t engine/egt/state -m "3"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "3"
mosquitto_pub -h localhost -t engine/boost/state -m "3"
mosquitto_pub -h localhost -t engine/coolant/state -m "3"
mosquitto_pub -h localhost -t engine/fuel/state -m "3"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "33"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "33"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
new_content="odo:333333
trip:333333"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "10"
mosquitto_pub -h localhost -t engine/egt/state -m "2"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "2"
mosquitto_pub -h localhost -t engine/boost/state -m "2"
mosquitto_pub -h localhost -t engine/coolant/state -m "2"
mosquitto_pub -h localhost -t engine/fuel/state -m "2"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "22"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "22"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:222222
trip:222222"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "5"
mosquitto_pub -h localhost -t engine/egt/state -m "1"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "1"
mosquitto_pub -h localhost -t engine/boost/state -m "1"
mosquitto_pub -h localhost -t engine/coolant/state -m "1"
mosquitto_pub -h localhost -t engine/fuel/state -m "1"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "11"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "11"
mosquitto_pub -h localhost -t indicator/illumination/state -m "1"
mosquitto_pub -h localhost -t indicator/foglight/state -m "1"
mosquitto_pub -h localhost -t indicator/defog/state -m "1"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "1"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "1"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "1"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "1"
mosquitto_pub -h localhost -t indicator/oillight/state -m "1"
mosquitto_pub -h localhost -t indicator/alt/state -m "1"
mosquitto_pub -h localhost -t indicator/glow/state -m "1"
new_content="odo:111111
trip:111111"
echo "$new_content" > odo.txt
# sleep 0.001
mosquitto_pub -h localhost -t engine/rpm/state -m "0"
mosquitto_pub -h localhost -t engine/egt/state -m "0"
mosquitto_pub -h localhost -t engine/oilpressure/state -m "0"
mosquitto_pub -h localhost -t engine/boost/state -m "0"
mosquitto_pub -h localhost -t engine/coolant/state -m "0"
mosquitto_pub -h localhost -t engine/fuel/state -m "0"
mosquitto_pub -h localhost -t cabin/outside_temp/state -m "00"
mosquitto_pub -h localhost -t cabin/speed_cv/state -m "00"
mosquitto_pub -h localhost -t indicator/illumination/state -m "0"
mosquitto_pub -h localhost -t indicator/foglight/state -m "0"
mosquitto_pub -h localhost -t indicator/defog/state -m "0"
mosquitto_pub -h localhost -t indicator/highbeam/state -m "0"
mosquitto_pub -h localhost -t indicator/leftturn/state -m "0"
mosquitto_pub -h localhost -t indicator/rightturn/state -m "0"
mosquitto_pub -h localhost -t indicator/brakewarn/state -m "0"
mosquitto_pub -h localhost -t indicator/oillight/state -m "0"
mosquitto_pub -h localhost -t indicator/alt/state -m "0"
mosquitto_pub -h localhost -t indicator/glow/state -m "0"
new_content="odo:000000
trip:000000"
echo "$new_content" > odo.txt
# sleep 0.001
